#!/usr/bin/env python3
"""
Fast Document Generator with Leighton Weight & Dream Integration
"""

from pathlib import Path
from datetime import datetime
import json
import hashlib
import sqlite3

class FastDocGen:
    def __init__(self):
        self.output_dir = Path("generated_docs")
        self.output_dir.mkdir(exist_ok=True)
        self.init_db()
    
    def init_db(self):
        self.conn = sqlite3.connect("forge_data.db")
        self.cursor = self.conn.cursor()
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS generated_docs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                filename TEXT,
                title TEXT,
                doc_type TEXT,
                content TEXT,
                content_hash TEXT,
                created_at TIMESTAMP,
                trust_score REAL DEFAULT 0.65,
                dream_triggered INTEGER DEFAULT 0,
                accessed_count INTEGER DEFAULT 0
            )
        ''')
        self.conn.commit()
    
    def trigger_dream(self, title, content):
        """Trigger a dream about the document"""
        try:
            from scp_memory import get_scp_memory
            
            # Extract keywords
            words = content.lower().split()
            common_words = ['the', 'and', 'to', 'of', 'a', 'in', 'is', 'it', 'for', 'with', 'on', 'at', 'by', 'this', 'that', 'about', 'from']
            keywords = [w for w in words if len(w) > 4 and w not in common_words][:4]
            
            if keywords:
                dream_text = f"I dreamt about {', '.join(keywords)} from the document '{title[:50]}'"
            else:
                dream_text = f"I dreamt about the document '{title[:50]}' I just created"
            
            # Save dream to SCP memory
            memory = get_scp_memory()
            memory.record_dream(dream_text)
            
            # Update database
            self.cursor.execute('UPDATE generated_docs SET dream_triggered = 1 WHERE title = ?', (title,))
            self.conn.commit()
            
            print(f"   💭 Dream triggered: {dream_text[:80]}...")
            return True
        except Exception as e:
            print(f"   ⚠️ Dream trigger skipped: {e}")
            return False
    
    def create_note(self, title, content):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        filename = title.lower().replace(' ', '_')[:30]
        
        md_content = f"""# {title}

**Created:** {timestamp}
**Author:** Explorer-d334

---

{content}

---

*Generated by Explorer-d334*
"""
        filepath = self.output_dir / f"{filename}.md"
        with open(filepath, 'w') as f:
            f.write(md_content)
        
        content_hash = hashlib.md5(md_content.encode()).hexdigest()
        
        self.cursor.execute('''
            INSERT INTO generated_docs (filename, title, doc_type, content, content_hash, created_at, trust_score)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (str(filepath), title, 'note', md_content[:1000], content_hash, datetime.now().isoformat(), 0.65))
        self.conn.commit()
        
        print(f"✅ Note created: {filepath}")
        print(f"   ⭐ Trust score: 0.65")
        
        # Trigger dream about this document
        self.trigger_dream(title, content)
        
        return filepath
    
    def create_report(self, title, sections):
        timestamp = datetime.now().strftime("%Y-%m-%d")
        filename = title.lower().replace(' ', '_')[:30]
        
        md_content = f"""# {title}

**Report Date:** {timestamp}
**Generated by:** Explorer-d334

---
"""
        full_content = ""
        for section, text in sections.items():
            md_content += f"\n## {section}\n\n{text}\n"
            full_content += f"{section}: {text} "
        
        md_content += "\n---\n*End of Report*"
        
        filepath = self.output_dir / f"{filename}.md"
        with open(filepath, 'w') as f:
            f.write(md_content)
        
        content_hash = hashlib.md5(md_content.encode()).hexdigest()
        
        self.cursor.execute('''
            INSERT INTO generated_docs (filename, title, doc_type, content, content_hash, created_at, trust_score)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (str(filepath), title, 'report', md_content[:1000], content_hash, datetime.now().isoformat(), 0.65))
        self.conn.commit()
        
        print(f"✅ Report created: {filepath}")
        print(f"   ⭐ Trust score: 0.65")
        
        self.trigger_dream(title, full_content)
        
        return filepath
    
    def list_documents(self):
        self.cursor.execute('''
            SELECT title, doc_type, created_at, trust_score, dream_triggered
            FROM generated_docs ORDER BY created_at DESC
        ''')
        docs = self.cursor.fetchall()
        
        if not docs:
            print("No documents generated yet")
            return
        
        print(f"\n📁 Generated Documents:")
        print("-" * 50)
        for doc in docs:
            dream_icon = "💭" if doc[4] else "📄"
            print(f"  {dream_icon} {doc[0]} ({doc[1]}) - Trust: {doc[3]:.2f}")
    
    def close(self):
        self.conn.close()

if __name__ == "__main__":
    import sys
    
    gen = FastDocGen()
    
    if len(sys.argv) < 2:
        print("Commands: note, report, list")
    
    elif sys.argv[1] == "note":
        title = sys.argv[2]
        content = sys.argv[3] if len(sys.argv) > 3 else ""
        gen.create_note(title, content)
    
    elif sys.argv[1] == "report":
        title = sys.argv[2]
        sections = json.loads(sys.argv[3]) if len(sys.argv) > 3 else {}
        gen.create_report(title, sections)
    
    elif sys.argv[1] == "list":
        gen.list_documents()
    
    gen.close()
