#!/usr/bin/env python3
"""
License enforcement for Explorer-d334
"""

import os
import json
import sqlite3
from pathlib import Path

class LicenseEnforcer:
    def __init__(self):
        self.license_file = Path("license.key")
        self.license_data = self.load_license()
        self.tier = self.license_data.get("tier", "personal") if self.license_data else "personal"
        self.features = self.license_data.get("features", {}) if self.license_data else {}
        self.init_db()
    
    def init_db(self):
        self.conn = sqlite3.connect("forge_data.db")
        self.cursor = self.conn.cursor()
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS usage_stats (
                metric TEXT PRIMARY KEY,
                value INTEGER DEFAULT 0
            )
        ''')
        self.conn.commit()
    
    def load_license(self):
        if self.license_file.exists():
            with open(self.license_file, 'r') as f:
                return json.load(f)
        if os.getenv("FORGE_DEVELOPMENT") == "1":
            return {"tier": "development", "features": {"commercial_use": True, "max_capsules": 9999}}
        return None
    
    def get_remaining_capsules(self):
        if self.tier != "personal":
            return 9999
        self.cursor.execute("SELECT value FROM usage_stats WHERE metric = 'custom_capsule_count'")
        row = self.cursor.fetchone()
        count = row[0] if row else 0
        return 10 - count  # Free tier limit: 10 capsules
    
    def check_capsule_limit(self):
        remaining = self.get_remaining_capsules()
        if remaining <= 0:
            print("❌ Free tier limit reached (10 custom capsules). Upgrade to Pro ($29/year) for unlimited.")
            return False
        return True
    
    def increment_capsule_count(self):
        if self.tier != "personal":
            return True
        self.cursor.execute("INSERT OR IGNORE INTO usage_stats (metric, value) VALUES ('custom_capsule_count', 0)")
        self.cursor.execute("UPDATE usage_stats SET value = value + 1 WHERE metric = 'custom_capsule_count'")
        self.conn.commit()
        return self.get_remaining_capsules() >= 0
    
    def add_code_watermark(self, code):
        if self.tier == "personal":
            watermark = "// Generated by Explorer-d334 (Personal Edition)\n// Upgrade to Pro at explorer-d334.com\n"
            return watermark + code
        return code
    
    def get_status(self):
        return {
            "tier": self.tier,
            "remaining_capsules": self.get_remaining_capsules(),
            "is_pro": self.tier in ["pro", "commercial", "enterprise", "development"]
        }
    
    def close(self):
        self.conn.close()

if __name__ == "__main__":
    e = LicenseEnforcer()
    print(f"Tier: {e.tier}")
    print(f"Remaining custom capsules: {e.get_remaining_capsules()}")
    e.close()
