#!/usr/bin/env python3
import subprocess
import json
import sys
import re
from pathlib import Path

class LocalAssistant:
    def __init__(self):
        self.capabilities = {
            "generate": self.generate_code,
            "explain": self.explain_code,
            "improve": self.improve_code,
            "find_bugs": self.find_bugs,
            "document": self.document_code
        }
    
    def generate_code(self, description):
        """Generate code from description"""
        # Parse description
        if "fibonacci" in description.lower():
            code = '''int fibonacci(int n) {
    if (n <= 1) return n;
    return fibonacci(n - 1) + fibonacci(n - 2);
}'''
        elif "factorial" in description.lower():
            code = '''int factorial(int n) {
    if (n <= 1) return 1;
    return n * factorial(n - 1);
}'''
        elif "prime" in description.lower():
            code = '''int is_prime(int n) {
    if (n <= 1) return 0;
    for (int i = 2; i * i <= n; i++)
        if (n % i == 0) return 0;
    return 1;
}'''
        else:
            code = f'''int generated_function(int n) {{
    // TODO: {description}
    return n * n;
}}'''
        return code
    
    def explain_code(self, code):
        """Explain what code does"""
        explanations = []
        if "fibonacci" in code:
            explanations.append("Calculates Fibonacci numbers recursively")
        if "factorial" in code:
            explanations.append("Computes factorial using recursion")
        if "for" in code and "i++" in code:
            explanations.append("Uses a loop to iterate over values")
        if "if" in code and "return" in code:
            explanations.append("Contains conditional logic")
        
        if not explanations:
            explanations.append("Standard C function with arithmetic")
        
        return "\n".join(explanations)
    
    def improve_code(self, code):
        """Suggest improvements"""
        improved = code
        suggestions = []
        
        if "recursion" in code and "fibonacci" in code:
            improved = '''int fibonacci(int n) {
    // Iterative version - more efficient
    int a = 0, b = 1, c;
    for (int i = 2; i <= n; i++) {
        c = a + b;
        a = b;
        b = c;
    }
    return n == 0 ? 0 : b;
}'''
            suggestions.append("Converted recursion to iteration for better performance")
        
        if "printf" in code and "\\n" not in code:
            suggestions.append("Add newlines to printf statements")
        
        return improved, suggestions
    
    def find_bugs(self, code):
        """Find potential bugs"""
        bugs = []
        if "malloc" in code and "free" not in code:
            bugs.append("Memory leak: allocated memory not freed")
        if "scanf" in code and "&" not in code:
            bugs.append("scanf missing address-of operator")
        if "=" in code and "==" not in code and "if (" in code:
            bugs.append("Possible assignment instead of comparison in if statement")
        return bugs if bugs else ["No obvious bugs found"]
    
    def document_code(self, code):
        """Generate documentation"""
        lines = code.split('\n')
        doc = "/**\n * Function: " + lines[0].strip() + "\n"
        doc += " * Generated by Forge Local Assistant\n"
        doc += " * \n * @param n Input parameter\n"
        doc += " * @return Computed result\n"
        doc += " */\n"
        return doc + code
    
    def process(self, command, input_text):
        if command in self.capabilities:
            return self.capabilities[command](input_text)
        return f"Unknown command: {command}"

if __name__ == "__main__":
    assistant = LocalAssistant()
    
    if len(sys.argv) < 2:
        print("Forge Local Assistant")
        print("Commands: generate, explain, improve, find_bugs, document")
        sys.exit(1)
    
    cmd = sys.argv[1]
    text = sys.stdin.read() if not sys.stdin.isatty() else " ".join(sys.argv[2:])
    
    result = assistant.process(cmd, text)
    print(result)
